### ISSUE TITLE
Push/pull to current branch

### ISSUE THREAD

**Issue by ArslanZamanov** [DmitryBarskov/git-tips#20]
`git push origin HEAD`
`git pull origin HEAD`

or add it to git config 

`git config push.default current --global`
*works only for push((

**Comment by DmitryBarskov** [comment]
@ArslanZamanov `git pull origin HEAD` doesn't work for me:

![image](https://user-images.githubusercontent.com/57901245/122916119-363c2100-d365-11eb-93e2-4b8313d40209.png)

**Comment by DmitryBarskov** [comment]
@ArslanZamanov I found out some interesting workarounds:

First, it is [thefuck](https://github.com/nvbn/thefuck) and [this example on stackoverflow](https://stackoverflow.com/a/47313649/14209416).

Second thing is that git can automatically infer the remote branch while first push, so you can just do `git push -u`, after that you will be able to pull without specifying remote and branch. Not to forget the `-u` flag I created an alias `push = push -u`.

Don't hesitate to submit a PR to resolve this issue.

**Comment by DmitryBarskov** [comment]
Another option it to create an alias:
```bash
alias gpull='git pull origin $(git branch --show-current)'
```
